//EXPORTAMOS UNA CONSTANTE CON EL NOMBRE DE LA ACCION QUE QUERMOS EJECUTAR
//ACA VAN LOS DIFERENTES TIPOS DE ACCIONES QUE VOY A QUERER REALIZAR EN MIS CATEGORIAS

export const ELECCION_CATEGORIA = "ELECCION_CATEGORIA"


//MIS ACCIONES QUE VAMOS A USAR EN EL REDUCER, POR ESO LAS EXPORTO
export const elegirCategoria = IdCategory => ({

    type: ELECCION_CATEGORIA,
    IdOfCategory: IdCategory

})